# -*- coding: utf-8 -*-
"""MDP_GridWorld_Incomplete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ReW3OoAz5P1SBeKBqQxxyx7z1sxguybV

# Mestrado em Inteligência Artificial 25/26

# Practical 2 — Markov Decision Processes (MDPs) with Gridworld

In the theory class you saw the **MDP framework** and the **Bellman equations**.
In this practical we will implement:

1. A small **Gridworld MDP**
2. **Policy Evaluation** (Bellman *expectation* backup)
3. **Value Iteration** (Bellman *optimality* backup)
4. A **visualization** of the value function and policy

We will use a **Sutton-style** gridworld:
- Grid: **4×4**
- Terminal states: **top-left (0,0)** and **bottom-right (3,3)**
- Reward: **-1 per step** (including bumping into walls)
- Discount factor: $\gamma = 0.9$ (slightly discounted)

What's the optimal behaviour?
"""

import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass
from typing import Dict, Tuple, List, Optional

np.set_printoptions(precision=3, suppress=True)

"""## 1) Gridworld MDP

We define:
- **States**: cells \((row,column)\)
- **Actions**: `U, D, L, R`
- **Transition**: deterministic (attempted move; if off-grid you stay)
- **Reward**: -1 each step; terminal states end the episode

We will implement an `env.step(state, action)` that returns:
`next_state, reward, done_flag`
"""

ACTIONS = ["U", "D", "L", "R"]
ACTION_TO_DELTA = {
    "U": (-1, 0),
    "D": ( 1, 0),
    "L": ( 0,-1),
    "R": ( 0, 1),
}

@dataclass(frozen=True)
class Gridworld:
    n_rows: int = 4
    n_cols: int = 4
    terminal_states: Tuple[Tuple[int,int], ...] = ((0,0), (3,3))
    step_reward: float = -1.0

    def states(self) -> List[Tuple[int,int]]:
        return [(row,column) for row in range(self.n_rows) for column in range(self.n_cols)]

    def is_terminal(self, state: Tuple[int,int]) -> bool:
        return state in self.terminal_states

    def step(self, state: Tuple[int,int], action: str) -> Tuple[Tuple[int,int], float, bool]:
        if self.is_terminal(state):
            return state, 0.0, True  # terminal state

        # TODO 1--- YOUR CODE STARTS HERE ---
       # Aplicar o delta correspondente à ação escolhida
        dr, dc = ACTION_TO_DELTA[action]
        new_row = state[0] + dr
        new_col = state[1] + dc

        # Se a nova posição sair fora da grelha, o agente fica no mesmo lugar
        # (bate na parede) — mas continua a pagar o custo de -1
        if 0 <= new_row < self.n_rows and 0 <= new_col < self.n_cols:
            next_state = (new_row, new_col)
        else:
            next_state = state  # fica no mesmo sítio

        reward = self.step_reward          # -1 por cada passo
        done_flag = self.is_terminal(next_state)
        # --- YOUR CODE ENDS HERE ---

        return next_state, reward, done_flag
    
env = Gridworld()
env.states()[:5], env.terminal_states

"""### Quick sanity checks"""

# From a non-terminal, moving into a wall keeps you in place but still costs -1
print("From (0,1) with U:", env.step((0,1), "U"))
# From a non-terminal, moving toward terminal
print("From (0,1) with L:", env.step((0,1), "L"))
# From terminal, stay terminal
print("From (0,0) with R:", env.step((0,0), "R"))

"""## 2) Utilities: indexing states and initializing V

We'll store $V$ (state-value function) as a 2D array `V[r,c]`.
"""

def zeros_V(env: Gridworld) -> np.ndarray:
    return np.zeros((env.n_rows, env.n_cols), dtype=float)

def all_states(env: Gridworld) -> List[Tuple[int,int]]:
    return env.states()

V0 = zeros_V(env)
V0

"""## 3) Policy definition

We start with a **uniform random policy**:
$\pi(a\mid s)=\frac{1}{4}$ for all non-terminal states.
"""

def uniform_random_policy(env: Gridworld) -> Dict[Tuple[int,int], Dict[str, float]]:
    policy = {}
    for s in env.states():
        if env.is_terminal(s):
            policy[s] = {a: 0.0 for a in ACTIONS} #ACTIONS = ["U", "D", "L", "R"]
        else:
            policy[s] = {a: 1.0/len(ACTIONS) for a in ACTIONS}
    return policy

policy = uniform_random_policy(env)
policy[(1,1)]

policy

"""## 4) Policy Evaluation (compute $V_{\pi}$)

Bellman expectation backup:

$
V(s) \leftarrow \sum_a \pi(a|s)\left[r(s,a) + \gamma V(s')\right]
$

### ✅ Your task
Fill in the two TODOs:
1. Compute the expected update for a single state (`bellman_expectation_update`)
2. Run iterative policy evaluation (`policy_evaluation`)
"""

def bellman_expectation_update(
    env: Gridworld, V: np.ndarray, policy: Dict[Tuple[int,int], Dict[str,float]],
    state: Tuple[int,int], gamma: float
) -> float:
    """Return the updated V(s) using the Bellman expectation backup."""
    if env.is_terminal(state):
        return 0.0

    # TODO 2: compute expected value over actions under pi(a|s)
    # Hints:
    #  - loop over actions
    v_new = 0.0
    # --- YOUR CODE STARTS HERE ---
    for a in ACTIONS:
        pi_a = policy[state][a]          # π(a|s)
        if pi_a == 0.0:
            continue
        ns, r, done = env.step(state, a) # s', r  (determinístico)
        v_new += pi_a * (r + gamma * V[ns[0], ns[1]])
    # --- YOUR CODE ENDS HERE ---
    return v_new


def policy_evaluation(
    env: Gridworld,
    policy: Dict[Tuple[int,int], Dict[str,float]],
    gamma: float,
    theta: float = 1e-6,
    max_iters: int = 10_000,
) -> Tuple[np.ndarray, int]:
    """Iterative policy evaluation."""
    V = zeros_V(env)

    for it in range(max_iters):
        delta = 0.0

        # TODO 3: sweep all states and update V in-place (or into a copy)
        # Use delta = max(delta, |V_new - V_old|). Stop if delta < theta.
        # --- YOUR CODE STARTS HERE ---
        for s in env.states():
            v_old = V[s[0], s[1]]
            v_new = bellman_expectation_update(env, V, policy, s, gamma)
            V[s[0], s[1]] = v_new
            delta = max(delta, abs(v_new - v_old))

        if delta < theta:
            return V, it + 1
        # --- YOUR CODE ENDS HERE ---

    return V, max_iters

gamma = 0.9
V_pi, iters = policy_evaluation(env, policy, gamma=gamma, theta=1e-8)
print("Converged in iterations:", iters)
V_pi

"""## 5) Value Iteration (approximate $V^{*}$)

Bellman optimality backup:

$
V(s) \leftarrow \max_a \left[r(s,a) + \gamma V(s')\right]
$

We then extract a greedy policy:
$\pi(s)=\arg\max_a\,[r(s,a)+\gamma V(s')]$
"""

def bellman_optimality_update(env: Gridworld, V: np.ndarray, s: Tuple[int,int], gamma: float) -> float:
    if env.is_terminal(s):
        return 0.0
    best = -np.inf
    for a in ACTIONS:
        ns, r, done = env.step(s, a)
        best = max(best, r + gamma * V[ns[0], ns[1]])
        # max instead of summing as we were doing before: v_new += p * (r + gamma * V[ns[0], ns[1]])
    return best

def value_iteration(
    env: Gridworld,
    gamma: float,
    theta: float = 1e-6,
    max_iters: int = 10_000,
) -> Tuple[np.ndarray, int]:
    V = zeros_V(env)
    for it in range(max_iters):
        delta = 0.0
        V_old = V.copy()
        for s in env.states():
            v_new = bellman_optimality_update(env, V_old, s, gamma)
            delta = max(delta, abs(v_new - V[s[0], s[1]]))
            V[s[0], s[1]] = v_new
        if delta < theta:
            return V, it + 1
    return V, max_iters

V_star, iters_vi = value_iteration(env, gamma=gamma, theta=1e-8)
print("Converged in iterations:", iters_vi)
V_star

def greedy_policy_from_V(env: Gridworld, V: np.ndarray, gamma: float) -> Dict[Tuple[int,int], str]:
    pi_greedy = {}
    for s in env.states():
        if env.is_terminal(s):
            pi_greedy[s] = "·"
            continue

        # TODO 4: get the best 'a' and 'q' (q is a one-step lookahead action value)
        # Hint: q(s, a) = r(s, a) + gamma * V(s')
        # --- YOUR CODE STARTS HERE ---
        best_a = None
        best_q = -np.inf
        for a in ACTIONS:
            ns, r, done = env.step(s, a)
            q = r + gamma * V[ns[0], ns[1]]   # q(s,a) = R_s^a + γ·V(s')
            if q > best_q:
                best_q = q
                best_a = a

        pi_greedy[s] = best_a
        # --- YOUR CODE ENDS HERE ---
    return pi_greedy

pi_star = greedy_policy_from_V(env, V_star, gamma=gamma)
pi_star[(2,2)], pi_star[(0,1)], pi_star[(1,0)]
print("\nExemplos de política ótima:")
print("  pi*(2,2) =", pi_star[(2,2)])
print("  pi*(0,1) =", pi_star[(0,1)])
print("  pi*(1,0) =", pi_star[(1,0)])

"""## 5.5) Compute the action-value function $Q^{\pi}$

So far, we computed **state-value functions**.
We now introduce the **action-value function**.


For a deterministic environment, the Bellman expectation equation for $Q^{\pi}$ is:

$$
Q^{\pi}(s,a) = r(s,a) + \gamma \sum_{a'} \pi(a'\mid s')\,Q^{\pi}(s',a')
$$

where $(s', r, done) = \texttt{step}(s,a)$.

We'll implement **iterative evaluation of $Q^{\pi}$** and verify:

$$
V^{\pi}(s) = \sum_a \pi(a\mid s)\,Q^{\pi}(s,a)
$$
"""

def zeros_Q(env: Gridworld) -> np.ndarray:
    # Q[r,c,a_index]
    return np.zeros((env.n_rows, env.n_cols, len(ACTIONS)), dtype=float)

def policy_evaluation_Q(
    env: Gridworld,
    pi: Dict[Tuple[int,int], Dict[str,float]],
    gamma: float,
    theta: float = 1e-6,
    max_iters: int = 10_000,
) -> Tuple[np.ndarray, int]:
    Q = zeros_Q(env)

    for it in range(max_iters):
        delta = 0.0
        Q_old = Q.copy()

        for (r,c) in env.states():
            s = (r,c)
            if env.is_terminal(s):
                Q[r,c,:] = 0.0
                continue

            for ai, a in enumerate(ACTIONS):
                ns, reward, done = env.step(s, a)
                nr, nc = ns

                # Expected over next action under pi
                exp_next = 0.0
                for aj, a2 in enumerate(ACTIONS):
                    exp_next += pi[ns][a2] * Q_old[nr, nc, aj] # 0.25 * Q[nr,nc,aj]

                q_new = reward + gamma * exp_next
                delta = max(delta, abs(q_new - Q[r,c,ai]))
                Q[r,c,ai] = q_new

        if delta < theta:
            return Q, it + 1

    return Q, max_iters

Q_pi, itq = policy_evaluation_Q(env, policy, gamma=gamma, theta=1e-8)
print("Q^pi converged in iterations:", itq)

"""## 6) Visualization

We will visualize:
- The value function as numbers inside the grid
- A policy as arrows

This is the part that makes Bellman backups “click”.
"""

ARROW = {"U":"↑", "D":"↓", "L":"←", "R":"→", "·":"·"}

def plot_grid_values_and_policy(
    env: Gridworld,
    V: np.ndarray,
    policy: Optional[Dict[Tuple[int,int], str]] = None,
    title: str = "",
    value_fmt: str = "{:.2f}",
):
    
    fig, ax = plt.subplots(figsize=(6,6))
    ax.set_title(title)

    # draw grid lines
    ax.set_xlim(0, env.n_cols)
    ax.set_ylim(0, env.n_rows)
    ax.set_xticks(np.arange(env.n_cols+1))
    ax.set_yticks(np.arange(env.n_rows+1))
    ax.grid(True)
    ax.invert_yaxis()  # row 0 at top
    ax.set_xticklabels([])
    ax.set_yticklabels([])

    # highlight terminal states
    for (r,c) in env.terminal_states:
        rect = plt.Rectangle((c, r), 1, 1, fill=True, alpha=0.15)
        ax.add_patch(rect)

    # put values + arrows
    for r in range(env.n_rows):
        for c in range(env.n_cols):
            s = (r,c)
            v = V[r,c]
            txt = value_fmt.format(v)
            ax.text(c+0.5, r+0.45, txt, ha="center", va="center", fontsize=12)
            if policy is not None:
                a = policy[s] if s in policy else "·"
                ax.text(c+0.5, r+0.78, ARROW.get(a,"·"), ha="center", va="center", fontsize=18)

    plt.show()

plot_grid_values_and_policy(env, V_pi, None, title="Policy evaluation: V^π (uniform random π)")

plot_grid_values_and_policy(env, V_star, pi_star, title="Value iteration: V* and greedy policy")

"""## 7) Exercises

### Exercise A — Change $\gamma$ and observe
Try `gamma = 0.5` and `gamma = 0.99`. Re-run policy evaluation and value iteration.
What changes in the value magnitude and the implied behaviour?

"""

print("\n=== Exercício A — Efeito de γ ===")
for g in [0.5, 0.99]:
    Vp, ip = policy_evaluation(env, policy, gamma=g, theta=1e-8)
    Vs, iv = value_iteration(env, gamma=g, theta=1e-8)
    ps = greedy_policy_from_V(env, Vs, gamma=g)
    print(f"\nγ = {g}")
    print(f"  Policy eval convergiu em {ip} iterações; V_pi min={Vp.min():.3f}, max={Vp.max():.3f}")
    print(f"  Value iter convergiu em {iv} iterações; V* min={Vs.min():.3f}, max={Vs.max():.3f}")
    plot_grid_values_and_policy(env, Vs, ps, title=f"Value_iteration_gamma_{str(g).replace('.','_')}")

"""### Exercise B — Add a “trap” cell
Pick a cell, e.g. (1,2), and make stepping *into* it give reward -10.
How does the optimal policy change? Tip: Inherit from the Gridworld class

Compare the number of iterations needed for policy iteration vs value iteration.
"""

print("\n=== Exercício B — Trap cell (1,2) ===")

@dataclass(frozen=True)
class GridworldTrap(Gridworld):
    trap_state: Tuple[int,int] = (1, 2)
    trap_reward: float = -10.0

    def step(self, state, action):
        next_state, reward, done_flag = super().step(state, action)
        # Se o agente aterrasse na trap, penaliza com -10
        if next_state == self.trap_state:
            reward = self.trap_reward
        return next_state, reward, done_flag

env_trap = GridworldTrap()
V_star_trap, iters_trap = value_iteration(env_trap, gamma=gamma, theta=1e-8)
pi_star_trap = greedy_policy_from_V(env_trap, V_star_trap, gamma=gamma)
print(f"Value iteration (trap) convergiu em {iters_trap} iterações")
plot_grid_values_and_policy(env_trap, V_star_trap, pi_star_trap, title="Value_iteration_trap_cell")

"""### Exercise C — Make the environment stochastic
Modify `env.step` so that with probability 0.8 the intended action happens, and with probability 0.1 you slip left/right (relative to intended direction).
What changes in $V^{*}$ and the greedy policy?

"""

print("\n=== Exercício C — Ambiente estocástico ===")

# Mapeamento de "desvio lateral" relativo a cada ação
SLIP_LEFT = {"U": "L", "D": "R", "L": "D", "R": "U"}
SLIP_RIGHT = {"U": "R", "D": "L", "L": "U", "R": "D"}

@dataclass(frozen=True)
@dataclass(frozen=True)
class GridworldStochastic(Gridworld):
    """Com prob 0.8 a ação pretendida ocorre;
       com prob 0.1 escorrega para a esquerda relativa;
       com prob 0.1 escorrega para a direita relativa."""

    def transitions(self, state, action):
        """Devolve lista de (prob, next_state, reward, done)."""
        if self.is_terminal(state):
            return [(1.0, state, 0.0, True)]
        outcomes = [
            (0.8, action),
            (0.1, SLIP_LEFT[action]),
            (0.1, SLIP_RIGHT[action]),
        ]
        result = []
        for prob, a in outcomes:
            dr, dc = ACTION_TO_DELTA[a]
            nr = state[0] + dr
            nc = state[1] + dc
            if 0 <= nr < self.n_rows and 0 <= nc < self.n_cols:
                ns = (nr, nc)
            else:
                ns = state
            reward = self.step_reward
            done = self.is_terminal(ns)
            result.append((prob, ns, reward, done))
        return result

    def step(self, state, action):
        """Amostragem determinística (usada para greedy_policy_from_V e display);
           para DP usamos transitions()."""
        # Usa o modo determinístico (probabilidade máxima) para visualização
        return super().step(state, action)

def bellman_optimality_update_stochastic(env: GridworldStochastic, V, s, gamma):
    if env.is_terminal(s):
        return 0.0
    best = -np.inf
    for a in ACTIONS:
        q_sa = sum(p * (r + gamma * V[ns[0], ns[1]])
                   for p, ns, r, done in env.transitions(s, a))
        best = max(best, q_sa)
    return best

def value_iteration_stochastic(env, gamma, theta=1e-6, max_iters=10_000):
    V = zeros_V(env)
    for it in range(max_iters):
        delta = 0.0
        V_old = V.copy()
        for s in env.states():
            v_new = bellman_optimality_update_stochastic(env, V_old, s, gamma)
            delta = max(delta, abs(v_new - V[s[0], s[1]]))
            V[s[0], s[1]] = v_new
        if delta < theta:
            return V, it + 1
    return V, max_iters

def greedy_policy_stochastic(env, V, gamma):
    pi = {}
    for s in env.states():
        if env.is_terminal(s):
            pi[s] = "·"
            continue
        best_a, best_q = None, -np.inf
        for a in ACTIONS:
            q = sum(p * (r + gamma * V[ns[0], ns[1]])
                    for p, ns, r, done in env.transitions(s, a))
            if q > best_q:
                best_q, best_a = q, a
        pi[s] = best_a
    return pi


env_stoch = GridworldStochastic()
V_star_stoch, iters_stoch = value_iteration_stochastic(env_stoch, gamma=gamma, theta=1e-8)
pi_star_stoch = greedy_policy_stochastic(env_stoch, V_star_stoch, gamma)
print(f"Value iteration (stochastic) convergiu em {iters_stoch} iterações")
plot_grid_values_and_policy(env_stoch, V_star_stoch, pi_star_stoch, title="Value_iteration_stochastic")

print("\nConcluído!")